# Generated by Django 5.2.6 on 2025-12-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_exam_description_exam_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
